name: pytest-workflow

on:
  push:
    branches:
      - main

env:
  PYTEST_ADDOPTS: "--color=yes"

jobs:
  workflow:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - name: Initialisation
      uses: actions/checkout@v2

    - name: Set up conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        activate-environment: conda-environment
        environment-file: .github/environment.yml

    - name: Install package
      run: python -m pip install .

    - name: Run pytest
      run: pytest
